package road_Fighter.server;

public enum Comandos {
	CREAR_SALA, OBTENER_SALAS, AL_LOBBY, ELIMINAR_SALA, UNIRSE_SALA, HACER_NADA, EMPEZAR_JUEGO, MOV_ARRIBA, MOV_ABAJO,
	MOV_IZQUIERDA, ACTUALIZAR_ARRIBA;
}
